### PR TITLE
add me :)

### PR DESCRIPTION
**Pull request by bluelhf**
adds me to the list! hopefully i did it right...

### CODE REVIEW

**Comment by rollecode** [comment]
@bluelhf Perfect, thx!

**Comment by bluelhf** [comment]
@ronilaukkarinen The innerHTML of the anchor tag is wrong (it doesn't include the Mastodon instance name) — should I open another PR?

**Comment by rollecode** [comment]
Not to worry, fixed it.

**Comment by bluelhf** [comment]
Alright, thanks! :)

**Pull request merged**
